
name: "pre-release"

on:
  push:
    branches:
      - "master"
    tags:
      - v*

jobs:
  build_jar:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Set Version
        uses: datamonsters/replace-action@v2
        with:
          files: 'pom.xml'
          replacements: 'Snapshot=${{ github.event.inputs.version_number }}'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Rename jar
        run: mv target/*.jar Tombstone-${{ github.event.inputs.version_number }}.jar
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: Tombstone-${{ github.event.inputs.version_number }}.jar
          if-no-files-found: error
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_jar
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: jar
          path: .
      - name: Show Artifacts
        run: ls -R
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version_number }}
          name: Version ${{ github.event.inputs.version_number }}
          draft: true
          prerelease: false
          artifacts: "*.jar"
          body: |
            ${{ github.event.inputs.info }}
            
          
